### ISSUE TITLE
error message: 'Process' object has no attribute '_counter'

### ISSUE THREAD

**Issue by ShaolongTan** [celery/billiard#189] opened 2016-08-09 06:39 UTC
Python version is:         Python 2.7.6
billiard version:             billiard 3.5.0.0
celery version:              4.0.0rc3 (0today8)

I have a task to run ansible playbook by celery apply_async, but I get below error message. If just run ansible playbook sole and not by celery. The ansible task work well. I don't sure the issue whether or not is my incorrectly usage with celery. Please help me check. Thanks you very much.
If you need the more detail issue information. Please let me know.

error message:
[2016-08-09 06:00:35,215: ERROR/PoolWorker-42] Task ansible_manager.playbook_exec[568ae7ad-d17f-43e6-b7ec-40c489569729] raised unexpected: AttributeError("'Process' object has no attribute '_counter'",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery-4.0.0rc3-py2.7.egg/celery/app/trace.py", line 358, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery-4.0.0rc3-py2.7.egg/celery/app/trace.py", line 609, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/vagrant/working/ansible_manager.py", line 87, in playbook_exec
    result = ansible_handle.ansible_playbook()
  File "/home/vagrant/working/ansible_handle/ansible_handle.py", line 64, in ansible_runner
    result = tqm.run(play)
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_queue_manager.py", line 212, in run
    self._initialize_processes(min(contenders))
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_queue_manager.py", line 107, in _initialize_processes
    self._result_prc = ResultProcess(self._final_q, self._workers)
  File "/usr/lib/python2.7/dist-packages/ansible/executor/process/result.py", line 62, in __init__
    super(ResultProcess, self).__init__()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 97, in __init__
    count = _current_process._counter.next()
AttributeError: 'Process' object has no attribute '_counter'

**Comment by ShaolongTan** [comment] 2016-08-09 06:43
Also, I run ansible playbook with below method.

from ansible.cli.playbook import PlaybookCLI

def run_playbook()
        playbook = "/home/ray/playbook.yaml"
        my_cli = PlaybookCLI(['', playbook, '-s'])
        my_cli.parse()
        results = my_cli.run()
        return results

**Comment by ShaolongTan** [comment] 2016-08-09 09:20
Downgrade celery to 3.1.23 and billiard to 3.3.0.23, I can't find the issue again.

**Comment by ShaolongTan** [comment] 2016-08-10 00:43
Maybe Ask have fix the bug at https://github.com/celery/billiard/commit/8e291e39fb8a5a962a759d3c5687ef59f923c90d

See the more detail from 
https://groups.google.com/forum/#!topic/celery-users/Yvn_u94DA0s

**Comment by ask** [comment] 2016-09-07 23:08
Closed by 8e291e39fb8a5a962a759d3c5687ef59f923c90d

**Closed by ask** 2016-09-07 23:08 UTC
Labels: Status: Needs Verification

**Comment by ramonz** [comment] 2016-09-12 11:07
the same issue here
proposed bugfix doesn't work. it produces new a new error
```
2016-09-12 14:00:16,368 | *.celery_app.py | _count_*_async:91 | ERROR | Error while count: AttributeError: 'Process' object has no attribute '_authkey'
Traceback (most recent call last):
  File "/home/*/tasks/counter.py", line 63, in _count_async
    click = TimeoutWrapper(get, 15)(id, prefix)
  File "/home/*/core/util/timeout_wrapper.py", line 18, in __call__
    p = Process(target=pmain, args=(child_pipe, self.func, args, kargs))
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 98, in __init__
    self._authkey = _current_process._authkey
AttributeError: 'Process' object has no attribute '_authkey'
```

TimeoutWrapper code
```
from multiprocessing import Process, Pipe, TimeoutError


class TimeoutWrapper():
    """Timeout wrapper using separate process"""
    def __init__(self, func, timeout):
        self.func = func
        self.timeout = timeout

    def __call__(self, *args, **kargs):
        """Run func with timeout"""
        def pmain(pipe, func, args, kargs):
            """Function to be called in separate process"""
            result = func(*args, **kargs) # call func with passed arguments
            pipe.send(result) # send result to pipe

        parent_pipe, child_pipe = Pipe() # Pipe for retrieving result of func
        p = Process(target=pmain, args=(child_pipe, self.func, args, kargs))
        p.start()
        p.join(self.timeout) # wait for prcoess to end

        if p.is_alive():
            p.terminate() # Timeout, kill
            # return None # or raise exception if None is acceptable result
            raise TimeoutError('Timeout exceeded')
        else:
            return parent_pipe.recv() # OK, get result

```

**Comment by ikalnytskyi** [comment] 2016-11-23 16:01
@ask Hey! May I ask what about the very same issue with `_authkey`? The traceback is shown in @ramonz message above. It's very essential to as I try to run Ansible playbook from Celery worker and it's unable to create a `Process` instance because it can't get some variables (like `_authkey`) from the `_current_process` which is `billiard.Process`.

**Comment by wuhfen** [comment] 2016-11-24 08:52
@ask I meet the _authkey issue in python2.7 django1.9.3 celery4.0 and ansible2.2.
```
[2016-11-24 08:29:16,346: ERROR/PoolWorker-1] Task testce.tasks.do_ansible[bf4b72fe-a45e-4b3c-a739-502da5513262] raised unexpected: AttributeError("'Process' object has no attribute '_authkey'",)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 368, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 623, in __protected_call__
    return self.run(*args, **kwargs)
  File "/tmp/djangoce/testce/tasks.py", line 42, in do_ansible
    ansiblex(vars1=task_path)
  File "/tmp/djangoce/testce/my_ansible.py", line 33, in ansiblex
    results = pbex.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 142, in run
    result = self._tqm.run(play=play)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 212, in run
    self._initialize_processes(min(contenders))
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 107, in _initialize_processes
    self._result_prc = ResultProcess(self._final_q, self._workers)
  File "/usr/lib/python2.7/site-packages/ansible/executor/process/result.py", line 62, in __init__
    super(ResultProcess, self).__init__()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 98, in __init__
    self._authkey = _current_process._authkey
AttributeError: 'Process' object has no attribute '_authkey'

```

**Comment by wuhfen** [comment] 2016-11-24 11:33
@ikalnytskyi When I change ansible worker.py code,It worked. Like this
step1   pip install billiard
step2   change file " /usr/lib/python2.7/site-packages/ansible/executor/process/worker.py"
```
            import billiard
           class WorkerProcess(billiard.Process): 
```

**Comment by ikalnytskyi** [comment] 2016-11-24 13:08
@wuhfen Yep, that's why I have this ugly workaround in my code https://github.com/ikalnytskyi/kostyor-openstack-ansible/commit/407ec033514600cd62f4931f199efd13405b0aae. But that's not a solution, the problem is in divergency between `multiprocessing` of Python 2.7 and `billiard` (which is mostly based on `multiprocessing` of Python 3.5).

**Comment by ikalnytskyi** [comment] 2016-11-26 08:11
I've prepared a simple patch that's enough to do backward compatibility just in case if anyone interested https://github.com/celery/billiard/pull/202.
